In [5]:
import cv2 as  cv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Create a sample image with some values
sample = np.full([10, 10], 100)
sample[1:-1,1:-1] = np.full([8,8], 150)
sample[3:-3,3:-3] = np.full([4,4], 0)
sample[4:-4, 4:-4] = np.full([2,2], 200)

# noramlize sample array
noramlized = sample / np.max(sample)
print(noramlized)

# Create a DataFrame with the original image array and actual indices
df = pd.DataFrame(sample[0:, 0:])

# Apply background styling directly to DataFrame using normalized values
styled_df = df.style.applymap(lambda value :f'background-color: rgb({int(value / np.max(sample) * 255)}, {int(value / np.max(sample) * 255)}, {int(value / np.max(sample) * 255)})')

# Display both the original image and the styled image
display(styled_df)

[[0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5 ]
 [0.5  0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.5 ]
 [0.5  0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.5 ]
 [0.5  0.75 0.75 0.   0.   0.   0.   0.75 0.75 0.5 ]
 [0.5  0.75 0.75 0.   1.   1.   0.   0.75 0.75 0.5 ]
 [0.5  0.75 0.75 0.   1.   1.   0.   0.75 0.75 0.5 ]
 [0.5  0.75 0.75 0.   0.   0.   0.   0.75 0.75 0.5 ]
 [0.5  0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.5 ]
 [0.5  0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.75 0.5 ]
 [0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5  0.5 ]]